version: 0.2
env:
  variables:
    MyVar: "Hello"
    REPOSITORY_URI: "183695703210.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-129174b85c5b"
    ImageName: "simple-docker-service-129174b85c5b"
    ImageTag: "latest"
  secrets-manager:
    DOCKER_HUB_USERNAME: "arn:aws:secretsmanager:us-east-1:183695703210:secret:prod/docker-login-iJ6OPC:DOCKER_HUB_USERNAME"
    DOCKER_HUB_PASSWORD: "arn:aws:secretsmanager:us-east-1:183695703210:secret:prod/docker-login-iJ6OPC:DOCKER_HUB_PASSWORD"
phases:
  pre_build:
    commands:
      - echo $MyVar
      - echo "Logging in to Docker"
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Building $REPOSITORY_URI:latest
      - docker build -t $REPOSITORY_URI:latest -f ./Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker images
  post_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 183695703210.dkr.ecr.us-east-1.amazonaws.com
      - docker push $REPOSITORY_URI:$IMAGE_TAG
