version: 0.2
env:
  variables:
    MyVar: "Hello"
  secrets-manager:
    DOCKER_HUB_USERNAME: "arn:aws:secretsmanager:us-east-1:183695703210:secret:prod/docker-login-iJ6OPC:DOCKER_HUB_USERNANE"
    DOCKER_HUB_PASSWORD: "arn:aws:secretsmanager:us-east-1:183695703210:secret:prod/docker-login-iJ6OPC:DOCKER_HUB_PASSWORD"
phases:
  pre_build:
    commands:
      - echo $MyVar
      - echo "Logging in to Docker"
      - echo $DOCKER_HUB_PASSWORD | docker login --username DOCKER_HUB_USERNANE --password-stdin
  build:
    commands:
      - echo $MyVar
      - docker build -t $ImageName -f ./Dockerfile .
      - docker images
  post_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 183695703210.dkr.ecr.us-east-1.amazonaws.com
      - docker tag $ImageName:latest 183695703210.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - docker push 183695703210.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
