version: 0.2

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: "planetary-api/docker-credentials:DOCKER_HUB_USERNAME"
    DOCKER_HUB_PASSWORD: "planetary-api/docker-credentials:DOCKER_HUB_PASSWORD"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub to avoid pull rate limits..."
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI:latest
      - docker push $ECR_URI:latest
      - echo "Generating imagedefinitions.json..."
      - printf '[{"name":"planetary-api","imageUri":"%s"}]' $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

  post_build:
    commands:
      - echo "Build completed. Image pushed to ECR."

artifacts:
  files:
    - imagedefinitions.json
